language: scala
dist: trusty
sudo: required
scala:
  - 2.11.11
rvm:
  - 2.4.2
jdk:
  - openjdk8
before_cache:
  - find $HOME/.ivy2/cache -name 'ivydata-*.properties' -delete
  - find $HOME/.sbt -name '*.lock' -delete
  - rm -rf $HOME/.sbt/0.13/dependency/module/dynamic
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - $HOME/.sbt
before_install:
  - gem install compass
install:
  - git submodule update --init --recursive
  - git clone https://github.com/Sanoma-CDA/maxmind-geoip2-scala.git $HOME/sanoma
  - cd $HOME/sanoma; sbt +publish-local; cd -
script: sbt test:compile test stage
