language: scala
dist: trusty
sudo: required
scala:
  - 2.12.7
jdk:
  - openjdk8
services:
  - mongodb
  - docker
env:
  matrix:
  - SBT_BIN=sbt -Dsbt.override.build.repos=true
  - MONGODB_URI=mongodb://127.0.0.1:27017/test
before_cache:
  - find $HOME/.ivy2/cache -name 'ivydata-*.properties' -delete
  - find $HOME/.sbt -name '*.lock' -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - $HOME/.sbt
before_install:
  - chmod +x bin/validate-code
  - git clone https://github.com/AlDanial/cloc.git $HOME/cloc
  - docker pull gawbul/docker-sge
install:
  - git submodule update --init --recursive
  - git clone https://github.com/felixgabler/maxmind-geoip2-scala.git $HOME/pizza
  - cd $HOME/pizza; sbt publishLocal; cd -
  - git clone https://github.com/zy4/scalajs-mithril.git $HOME/scalajs-mithril
  - cd $HOME/scalajs-mithril; sbt publishLocal; cd -
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom@9.12.0
script:
 - bin/validate-code
 - $SBT_BIN test:compile test stage
 - $HOME/cloc/cloc $(git ls-files)
