language: scala
dist: xenial
sudo: required
scala:
  - 2.12.8
jdk:
  - openjdk8
services:
  - mongodb
  - docker
env:
  global:
    - SBT_BIN=sbt -Dsbt.override.build.repos=true
    - MONGODB_URI=mongodb://127.0.0.1:27017/test
before_cache:
  - find $HOME/.ivy2/cache -name 'ivydata-*.properties' -delete
  - find $HOME/.sbt -name '*.lock' -delete
cache:
  yarn: true
  directories:
  - "$HOME/.ivy2/cache"
  - $HOME/.sbt
before_install:
  - chmod +x bin/validate-code
  - git clone https://github.com/AlDanial/cloc.git $HOME/cloc
install:
  - git submodule update --init --recursive
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - cd frontend; yarn install; cd -
script:
 - bin/validate-code
 - $SBT_BIN test stage
 - cd frontend
 - yarn run test:unit
 - cd -
 - $HOME/cloc/cloc $(git ls-files)
