language: scala
dist: trusty
sudo: required
scala:
  - 2.12.4
rvm:
  - 2.4.2
jdk:
  - openjdk8
before_cache:
  - find $HOME/.ivy2/cache -name 'ivydata-*.properties' -delete
  - find $HOME/.sbt -name '*.lock' -delete
  - rm -rf $HOME/.sbt/0.13/dependency/module/dynamic
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - $HOME/.sbt
before_install:
  - gem install compass
install:
  - git submodule update --init --recursive
  - git clone https://github.com/felixgabler/maxmind-geoip2-scala.git $HOME/pizza
  - cd $HOME/pizza; sbt publishLocal; cd -
  - git clone https://github.com/zy4/scalajs-mithril.git $HOME/scalajs-mithril
  - cd $HOME/scalajs-mithril; sbt publishLocal; cd -
script: sbt test:compile test stage
