version: '3.5'
# Here we configure the Containers to run.
services:

  toolkit:
    build: .
    env_file:
      - conf/.env
    container_name: toolkit
    ports:
    - 1234:1234
    volumes:
    - .:/app
    links:
    - mongodb
    depends_on:
    - mongodb

  # The container for the MongoDB Database
  mongodb:
    image: mongo:4.0
    container_name: tk-mongodb
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/data/log
    # uncomment the following lines to setup auth for mongo
    # - MONGO_INITDB_ROOT_USERNAME=root
    # - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
    volumes:
    - mongodb:/data/db
    ports:
    - 27017:27017
    command: mongod

volumes:
  mongodb:

# maybe we could also use a docker network if necessary
