version: '3.7'
# Here we configure the Containers to run.
services:

  toolkit:
    image: proteinevolution/toolkit-docker:latest
    container_name: toolkit
    environment:
    - SUBMIT_MODE=LOCAL
    - SBT_OPTS=-Xms2G -Xmx4G -Xss2M
    stdin_open: true
    tty: true
    ports:
    - 1234:1234
    - 8080:8080
    volumes:
    - .:/toolkit
    links:
    - mongodb
    depends_on:
    - mongodb
    networks:
      tk-network:
        ipv4_address: 174.18.0.2

  # The container for the MongoDB Database
  mongodb:
    image: mongo:4.0
    container_name: tk-mongodb
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/data/log
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=rootPassXX
    volumes:
    - mongodb:/data/db
    ports:
    - 27017:27017
    command: mongod --auth
    networks:
      tk-network:
        ipv4_address: 174.18.0.3

volumes:
  mongodb:

networks:
  tk-network:
    name: tk-network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 174.18.0.1/24
