name: Backend

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-backend:
    runs-on: ubuntu-latest
    name: Build Server
    env:
      SBT_BIN: sbt -Dsbt.override.build.repos=true
      MONGODB_URI: mongodb://127.0.0.1:27017/test

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.m2
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.1

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - name: Install local dependencies
        run: ./bin/install-local-deps.sh

      - name: Compile sbt
        run: sbt compile stage
        timeout-minutes: 30

      - name: Run backend tests
        run: sbt coverage test

      - name: Create coverage report
        run: sbt coverageReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  scalafmt:
    runs-on: ubuntu-latest
    name: Lint with Scalafmt

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Formatting Scala
        run: sbt scalafmt scalafmtSbt && git diff --exit-code

      - name: Count Lines of Code (cloc)
        uses: djdefi/cloc-action@2
